// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJOWKmo8e_ooR1wmCFZ9FnfueRb0DeZI',
    appId: '1:992250215486:web:36423e6420239b9ab3a56f',
    messagingSenderId: '992250215486',
    projectId: 'stoic-bot-fc1ec',
    authDomain: 'stoic-bot-fc1ec.firebaseapp.com',
    storageBucket: 'stoic-bot-fc1ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcAsEdjrcbK62wGSRnuDx0MFkUOzrIOE',
    appId: '1:992250215486:android:2db23647c2cc4d0ab3a56f',
    messagingSenderId: '992250215486',
    projectId: 'stoic-bot-fc1ec',
    storageBucket: 'stoic-bot-fc1ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: '992250215486',
    projectId: 'stoic-bot-fc1ec',
    storageBucket: 'stoic-bot-fc1ec.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: '992250215486',
    projectId: 'stoic-bot-fc1ec',
    storageBucket: 'stoic-bot-fc1ec.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
